secrets:
  notion_key: notion_integration/notion_key.txt
  notion_database: notion_integration/notion_database.txt
  google: notification/google.txt

notion:
  url_query: https://api.notion.com/v1/databases/{database_id}/query
  url_add_pages: https://api.notion.com/v1/pages
  headers:
    Authorization: "Bearer {notion_key}"
    accept: "application/json"
    Notion-Version: "2022-06-28"
    content-type: "application/json"
